## 1. Read in a csv file line-by-line and process

#### Import all required modules

In [1]:
import os
import pandas as pd
import numpy as np

#### Navigate to your working directory

In [2]:
os.chdir("/Users/nastassiapatin/OneDrive - SCCWRP/Bioinformatics/MAMBO/GOMECC")
file = "GOMECC-DwC-data.csv"

In [3]:
dwc = pd.read_csv(file, dtype={
    'occurrenceRemarks': 'string'})
dwc.head()

,id,datasetID,basisOfRecord,occurrenceID,recordedBy,organismQuantity,organismQuantityType,occurrenceStatus,associatedSequences,occurrenceRemarks,...,scientificNameID,scientificName,nameAccordingTo,kingdom,phylum,class,order,family,genus,taxonRank
0,GOMECC4_27N_Sta1_DCM_A_16S_occ00c4c1c65d8669ed...,noaa-aoml-gomecc4,MaterialSample,GOMECC4_27N_Sta1_DCM_A_16S_occ00c4c1c65d8669ed...,Luke Thompson | Katherine Silliman,18,DNA sequence reads,present,https://www.ncbi.nlm.nih.gov/sra/SRR26148187 |...,<NA>,...,urn:lsid:marinespecies.org:taxname:392750,Alphaproteobacteria,WoRMS,Bacteria,Proteobacteria,Alphaproteobacteria,NaN,NaN,NaN,Class
1,GOMECC4_27N_Sta1_DCM_A_16S_occ00e6c13fe86364a5...,noaa-aoml-gomecc4,MaterialSample,GOMECC4_27N_Sta1_DCM_A_16S_occ00e6c13fe86364a5...,Luke Thompson | Katherine Silliman,36,DNA sequence reads,present,https://www.ncbi.nlm.nih.gov/sra/SRR26148187 |...,<NA>,...,urn:lsid:marinespecies.org:taxname:392750,Alphaproteobacteria,WoRMS,Bacteria,Proteobacteria,Alphaproteobacteria,NaN,NaN,NaN,Class
2,GOMECC4_27N_Sta1_DCM_A_16S_occ015dad1fafca9094...,noaa-aoml-gomecc4,MaterialSample,GOMECC4_27N_Sta1_DCM_A_16S_occ015dad1fafca9094...,Luke Thompson | Katherine Silliman,49,DNA sequence reads,present,https://www.ncbi.nlm.nih.gov/sra/SRR26148187 |...,<NA>,...,urn:lsid:marinespecies.org:taxname:416268,Thermoplasmata,WoRMS,Archaea,Euryarchaeota,Thermoplasmata,NaN,NaN,NaN,Class
3,GOMECC4_27N_Sta1_DCM_A_16S_occ019c88c6ade406f7...,noaa-aoml-gomecc4,MaterialSample,GOMECC4_27N_Sta1_DCM_A_16S_occ019c88c6ade406f7...,Luke Thompson | Katherine Silliman,2,DNA sequence reads,present,https://www.ncbi.nlm.nih.gov/sra/SRR26148187 |...,<NA>,...,urn:lsid:marinespecies.org:taxname:570969,Rickettsiales,WoRMS,Bacteria,Proteobacteria,Alphaproteobacteria,Rickettsiales,NaN,NaN,Order
4,GOMECC4_27N_Sta1_DCM_A_16S_occ02dfb0869af4bf54...,noaa-aoml-gomecc4,MaterialSample,GOMECC4_27N_Sta1_DCM_A_16S_occ02dfb0869af4bf54...,Luke Thompson | Katherine Silliman,3,DNA sequence reads,present,https://www.ncbi.nlm.nih.gov/sra/SRR26148187 |...,<NA>,...,urn:lsid:marinespecies.org:taxname:6,Bacteria,WoRMS,Bacteria,NaN,NaN,NaN,NaN,NaN,Kingdom

### Pre-processing: drop unnecessary columns and split the ASV hashes into a separate column

In [4]:
dwc = dwc.drop(['datasetID', 
                'basisOfRecord', 
                'recordedBy', 
                'parentEventID',
                'organismQuantityType', 
                'occurrenceStatus', 
                'associatedSequences', 
                'occurrenceRemarks', 
                'sampleSizeUnit'], axis=1)
dwc[['ASV', 'hash']] = dwc['taxonID'].str.split(':', expand=True)
dwc.head()

,id,occurrenceID,organismQuantity,materialSampleID,eventID,eventDate,samplingProtocol,sampleSizeValue,locationID,waterBody,...,nameAccordingTo,kingdom,phylum,class,order,family,genus,taxonRank,ASV,hash
0,GOMECC4_27N_Sta1_DCM_A_16S_occ00c4c1c65d8669ed...,GOMECC4_27N_Sta1_DCM_A_16S_occ00c4c1c65d8669ed...,18,SAMN37516094,GOMECC4_27N_Sta1_DCM_A_16S,2021-09-14T11:00-04:00,CTD rosette,16187,27N_Sta1,Atlantic Ocean,...,WoRMS,Bacteria,Proteobacteria,Alphaproteobacteria,NaN,NaN,NaN,Class,ASV,00c4c1c65d8669ed9f07abe149f9a01d
1,GOMECC4_27N_Sta1_DCM_A_16S_occ00e6c13fe86364a5...,GOMECC4_27N_Sta1_DCM_A_16S_occ00e6c13fe86364a5...,36,SAMN37516094,GOMECC4_27N_Sta1_DCM_A_16S,2021-09-14T11:00-04:00,CTD rosette,16187,27N_Sta1,Atlantic Ocean,...,WoRMS,Bacteria,Proteobacteria,Alphaproteobacteria,NaN,NaN,NaN,Class,ASV,00e6c13fe86364a5084987093afa1916
2,GOMECC4_27N_Sta1_DCM_A_16S_occ015dad1fafca9094...,GOMECC4_27N_Sta1_DCM_A_16S_occ015dad1fafca9094...,49,SAMN37516094,GOMECC4_27N_Sta1_DCM_A_16S,2021-09-14T11:00-04:00,CTD rosette,16187,27N_Sta1,Atlantic Ocean,...,WoRMS,Archaea,Euryarchaeota,Thermoplasmata,NaN,NaN,NaN,Class,ASV,015dad1fafca90944d905beb2a980bc3
3,GOMECC4_27N_Sta1_DCM_A_16S_occ019c88c6ade406f7...,GOMECC4_27N_Sta1_DCM_A_16S_occ019c88c6ade406f7...,2,SAMN37516094,GOMECC4_27N_Sta1_DCM_A_16S,2021-09-14T11:00-04:00,CTD rosette,16187,27N_Sta1,Atlantic Ocean,...,WoRMS,Bacteria,Proteobacteria,Alphaproteobacteria,Rickettsiales,NaN,NaN,Order,ASV,019c88c6ade406f731954f38e3461564
4,GOMECC4_27N_Sta1_DCM_A_16S_occ02dfb0869af4bf54...,GOMECC4_27N_Sta1_DCM_A_16S_occ02dfb0869af4bf54...,3,SAMN37516094,GOMECC4_27N_Sta1_DCM_A_16S,2021-09-14T11:00-04:00,CTD rosette,16187,27N_Sta1,Atlantic Ocean,...,WoRMS,Bacteria,NaN,NaN,NaN,NaN,NaN,Kingdom,ASV,02dfb0869af4bf549d290d48e66e2196

### Pre-processing: Separate the table into 16S and 18S data sets

In [5]:
dwc[['parentEventID', 'markerGene']] = dwc['eventID'].str.rsplit('_', n=1, expand=True)
dwc.head()

,id,occurrenceID,organismQuantity,materialSampleID,eventID,eventDate,samplingProtocol,sampleSizeValue,locationID,waterBody,...,phylum,class,order,family,genus,taxonRank,ASV,hash,parentEventID,markerGene
0,GOMECC4_27N_Sta1_DCM_A_16S_occ00c4c1c65d8669ed...,GOMECC4_27N_Sta1_DCM_A_16S_occ00c4c1c65d8669ed...,18,SAMN37516094,GOMECC4_27N_Sta1_DCM_A_16S,2021-09-14T11:00-04:00,CTD rosette,16187,27N_Sta1,Atlantic Ocean,...,Proteobacteria,Alphaproteobacteria,NaN,NaN,NaN,Class,ASV,00c4c1c65d8669ed9f07abe149f9a01d,GOMECC4_27N_Sta1_DCM_A,16S
1,GOMECC4_27N_Sta1_DCM_A_16S_occ00e6c13fe86364a5...,GOMECC4_27N_Sta1_DCM_A_16S_occ00e6c13fe86364a5...,36,SAMN37516094,GOMECC4_27N_Sta1_DCM_A_16S,2021-09-14T11:00-04:00,CTD rosette,16187,27N_Sta1,Atlantic Ocean,...,Proteobacteria,Alphaproteobacteria,NaN,NaN,NaN,Class,ASV,00e6c13fe86364a5084987093afa1916,GOMECC4_27N_Sta1_DCM_A,16S
2,GOMECC4_27N_Sta1_DCM_A_16S_occ015dad1fafca9094...,GOMECC4_27N_Sta1_DCM_A_16S_occ015dad1fafca9094...,49,SAMN37516094,GOMECC4_27N_Sta1_DCM_A_16S,2021-09-14T11:00-04:00,CTD rosette,16187,27N_Sta1,Atlantic Ocean,...,Euryarchaeota,Thermoplasmata,NaN,NaN,NaN,Class,ASV,015dad1fafca90944d905beb2a980bc3,GOMECC4_27N_Sta1_DCM_A,16S
3,GOMECC4_27N_Sta1_DCM_A_16S_occ019c88c6ade406f7...,GOMECC4_27N_Sta1_DCM_A_16S_occ019c88c6ade406f7...,2,SAMN37516094,GOMECC4_27N_Sta1_DCM_A_16S,2021-09-14T11:00-04:00,CTD rosette,16187,27N_Sta1,Atlantic Ocean,...,Proteobacteria,Alphaproteobacteria,Rickettsiales,NaN,NaN,Order,ASV,019c88c6ade406f731954f38e3461564,GOMECC4_27N_Sta1_DCM_A,16S
4,GOMECC4_27N_Sta1_DCM_A_16S_occ02dfb0869af4bf54...,GOMECC4_27N_Sta1_DCM_A_16S_occ02dfb0869af4bf54...,3,SAMN37516094,GOMECC4_27N_Sta1_DCM_A_16S,2021-09-14T11:00-04:00,CTD rosette,16187,27N_Sta1,Atlantic Ocean,...,NaN,NaN,NaN,NaN,NaN,Kingdom,ASV,02dfb0869af4bf549d290d48e66e2196,GOMECC4_27N_Sta1_DCM_A,16S

In [6]:
gomecc_16S = dwc[dwc['markerGene'] == '16S']
gomecc_18S = dwc[dwc['markerGene'] == '18S']
gomecc_16S.head()

,id,occurrenceID,organismQuantity,materialSampleID,eventID,eventDate,samplingProtocol,sampleSizeValue,locationID,waterBody,...,phylum,class,order,family,genus,taxonRank,ASV,hash,parentEventID,markerGene
0,GOMECC4_27N_Sta1_DCM_A_16S_occ00c4c1c65d8669ed...,GOMECC4_27N_Sta1_DCM_A_16S_occ00c4c1c65d8669ed...,18,SAMN37516094,GOMECC4_27N_Sta1_DCM_A_16S,2021-09-14T11:00-04:00,CTD rosette,16187,27N_Sta1,Atlantic Ocean,...,Proteobacteria,Alphaproteobacteria,NaN,NaN,NaN,Class,ASV,00c4c1c65d8669ed9f07abe149f9a01d,GOMECC4_27N_Sta1_DCM_A,16S
1,GOMECC4_27N_Sta1_DCM_A_16S_occ00e6c13fe86364a5...,GOMECC4_27N_Sta1_DCM_A_16S_occ00e6c13fe86364a5...,36,SAMN37516094,GOMECC4_27N_Sta1_DCM_A_16S,2021-09-14T11:00-04:00,CTD rosette,16187,27N_Sta1,Atlantic Ocean,...,Proteobacteria,Alphaproteobacteria,NaN,NaN,NaN,Class,ASV,00e6c13fe86364a5084987093afa1916,GOMECC4_27N_Sta1_DCM_A,16S
2,GOMECC4_27N_Sta1_DCM_A_16S_occ015dad1fafca9094...,GOMECC4_27N_Sta1_DCM_A_16S_occ015dad1fafca9094...,49,SAMN37516094,GOMECC4_27N_Sta1_DCM_A_16S,2021-09-14T11:00-04:00,CTD rosette,16187,27N_Sta1,Atlantic Ocean,...,Euryarchaeota,Thermoplasmata,NaN,NaN,NaN,Class,ASV,015dad1fafca90944d905beb2a980bc3,GOMECC4_27N_Sta1_DCM_A,16S
3,GOMECC4_27N_Sta1_DCM_A_16S_occ019c88c6ade406f7...,GOMECC4_27N_Sta1_DCM_A_16S_occ019c88c6ade406f7...,2,SAMN37516094,GOMECC4_27N_Sta1_DCM_A_16S,2021-09-14T11:00-04:00,CTD rosette,16187,27N_Sta1,Atlantic Ocean,...,Proteobacteria,Alphaproteobacteria,Rickettsiales,NaN,NaN,Order,ASV,019c88c6ade406f731954f38e3461564,GOMECC4_27N_Sta1_DCM_A,16S
4,GOMECC4_27N_Sta1_DCM_A_16S_occ02dfb0869af4bf54...,GOMECC4_27N_Sta1_DCM_A_16S_occ02dfb0869af4bf54...,3,SAMN37516094,GOMECC4_27N_Sta1_DCM_A_16S,2021-09-14T11:00-04:00,CTD rosette,16187,27N_Sta1,Atlantic Ocean,...,NaN,NaN,NaN,NaN,NaN,Kingdom,ASV,02dfb0869af4bf549d290d48e66e2196,GOMECC4_27N_Sta1_DCM_A,16S

In [13]:
gomecc_16S_sub = gomecc_16S[['parentEventID', 'markerGene', 'hash']]
gomecc_16S_sub.head()

            parentEventID markerGene                              hash
0  GOMECC4_27N_Sta1_DCM_A        16S  00c4c1c65d8669ed9f07abe149f9a01d
1  GOMECC4_27N_Sta1_DCM_A        16S  00e6c13fe86364a5084987093afa1916
2  GOMECC4_27N_Sta1_DCM_A        16S  015dad1fafca90944d905beb2a980bc3
3  GOMECC4_27N_Sta1_DCM_A        16S  019c88c6ade406f731954f38e3461564
4  GOMECC4_27N_Sta1_DCM_A        16S  02dfb0869af4bf549d290d48e66e2196

In [14]:
gomecc_16S_sub[gomecc_16S_sub['parentEventID'].str.contains('FLSTRAITS')]

,parentEventID,markerGene,hash
53387,GOMECC4_FLSTRAITS_Sta121_DCM_A,16S,000094731d4984ed41435a1bf65b7ef2
53388,GOMECC4_FLSTRAITS_Sta121_DCM_A,16S,00180b3b3075e3ac19806329a5aa8531
53389,GOMECC4_FLSTRAITS_Sta121_DCM_A,16S,00232f374cfc930f3fffbaef0d0c6d80
53390,GOMECC4_FLSTRAITS_Sta121_DCM_A,16S,005117bfb82a9facd3218e5339d060b0
53391,GOMECC4_FLSTRAITS_Sta121_DCM_A,16S,014df9fe1ea26f69886fdf906a357eb4
...,...,...,...
65363,GOMECC4_FLSTRAITS_Sta123_Surface_C,16S,fdef6f8b24131cf458cab06a1fb9234c
65364,GOMECC4_FLSTRAITS_Sta123_Surface_C,16S,fe0c9b71f348f2d5b630b2b7ef4c3a25
65365,GOMECC4_FLSTRAITS_Sta123_Surface_C,16S,fea2c2e3cf67ca23d22aa594e15fbb19
65366,GOMECC4_FLSTRAITS_Sta123_Surface_C,16S,feaf7d4877fba14883828e5fca89566c
65367,GOMECC4_FLSTRAITS_Sta123_Surface_C,16S,ff422655e506d8e83a87e4098951a15d

### 1. Make the ASV tables

In [44]:
gomecc_16S_asvs = gomecc_16S[['parentEventID', 'organismQuantity', 'hash']]
gomecc_18S_asvs = gomecc_18S[['parentEventID', 'organismQuantity', 'hash']]
gomecc_16S_asvs.head()
gomecc_18S_asvs.head()

            parentEventID  organismQuantity                              hash
0  GOMECC4_27N_Sta1_DCM_A                18  00c4c1c65d8669ed9f07abe149f9a01d
1  GOMECC4_27N_Sta1_DCM_A                36  00e6c13fe86364a5084987093afa1916
2  GOMECC4_27N_Sta1_DCM_A                49  015dad1fafca90944d905beb2a980bc3
3  GOMECC4_27N_Sta1_DCM_A                 2  019c88c6ade406f731954f38e3461564
4  GOMECC4_27N_Sta1_DCM_A                 3  02dfb0869af4bf549d290d48e66e2196

#### Convert to wide format

In [52]:
gomecc_16S_asvs_wide = gomecc_16S_asvs.groupby(['parentEventID', 'hash']).organismQuantity.first().unstack().fillna(0).T
gomecc_18S_asvs_wide = gomecc_18S_asvs.groupby(['parentEventID', 'hash']).organismQuantity.first().unstack().fillna(0).T

#### Save as csv files

In [53]:
gomecc_16S_asvs_wide.to_csv('GOMECC_16S_ASV_table.csv')
gomecc_18S_asvs_wide.to_csv('GOMECC_18S_ASV_table.csv')

### 2. Make the taxonomy tables

In [160]:
def format_taxonomy_table(df, gene):
    tax = df[['verbatimIdentification', 'taxonID', 'kingdom', 'phylum', 'class', 'order', 'family', 'genus']]
    tax.loc[:, 'hash'] = tax.loc[:, 'taxonID'].str.split(':', expand=True)[1]
    tax.loc[:, ['Domain', 'Phylum', 'Class', 'Order', 'Family', 'Genus', 'Species']] = tax.loc[:, 'verbatimIdentification'].str.split(';', n=6, expand=True)
    tax = tax.drop(['verbatimIdentification', 'taxonID'], axis=1)
    # Some 18S 'verbatimIdentification' fields only have species name; for these we pull out the WoRMS taxonomy fields
    if (gene=='18S'):
        tax.loc[(tax['Domain'] != 'Eukaryota') & (tax['Domain'] != 'Bacteria') & (tax['Domain'] != 'Archaea'), 'Species'] = tax['Domain']
        tax.loc[(tax['Domain'] != 'Eukaryota') & (tax['Domain'] != 'Bacteria') & (tax['Domain'] != 'Archaea'), 'Class'] = tax['class']
        tax.loc[(tax['Domain'] != 'Eukaryota') & (tax['Domain'] != 'Bacteria') & (tax['Domain'] != 'Archaea'), 'Order'] = tax['order']
        tax.loc[(tax['Domain'] != 'Eukaryota') & (tax['Domain'] != 'Bacteria') & (tax['Domain'] != 'Archaea'), 'Family'] = tax['family']
        tax.loc[(tax['Domain'] != 'Eukaryota') & (tax['Domain'] != 'Bacteria') & (tax['Domain'] != 'Archaea'), 'Genus'] = tax['genus']
        # Some unassigned 18S taxa have "nan" as Domain, we can rename these to be 'Unassigned'
        tax.loc[(tax['Species'] == 'Unassigned'), 'Domain'] = 'Unassigned'
        # The WoRMS "kingdoms" are all eukaryotic (fungi, protozoa, chromista, etc.) so we assign all those to 'Eukaryota' 
        tax.loc[(tax['Domain'] != 'Eukaryota') & (tax['Domain'] != 'Unassigned'), 'Domain'] = 'Eukaryota'
        pass
    tax = tax.drop(['kingdom', 'phylum', 'class', 'order', 'family', 'genus'], axis=1)
    tax = tax.drop_duplicates()
    return(tax)

In [162]:
tax_16S = format_taxonomy_table(gomecc_16S, '16S')
tax_18S = format_taxonomy_table(gomecc_18S, '18S')

/var/folders/6n/rgpvqypd433dd8y5lhhddmxw0000gn/T/ipykernel_93469/233737532.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tax.loc[:, 'hash'] = tax.loc[:, 'taxonID'].str.split(':', expand=True)[1]

In [163]:
tax_18S.head()

,hash,Domain,Phylum,Class,Order,Family,Genus,Species
165158,36aa75f9b28f5f831c2d631ba65c2bcb,Eukaryota,NaN,Copepoda,Calanoida,Calanidae,Neocalanus,NaN
165159,4e38e8ced9070952b314e1880bede1ca,Eukaryota,NaN,Copepoda,Calanoida,Clausocalanidae,Clausocalanus,NaN
165160,2a31e5c01634165da99e7381279baa75,Eukaryota,NaN,Copepoda,Calanoida,Paracalanidae,Acrocalanus,NaN
165161,ecee60339b2fb88ea6d1c8d18054bed4,Eukaryota,NaN,Dinophyceae,NaN,NaN,NaN,NaN
165162,fa1f1a97dd4ae7c826009186bad26384,Eukaryota,NaN,Dinophyceae,Gymnodiniales,Gymnodiniaceae,NaN,NaN

In [136]:
tax_16S.to_csv('GOMECC_16S_taxonomy_table.csv', index=None)
tax_18S.to_csv('GOMECC_18S_taxonomy_table.csv', index=None)

### 3. Make the metadata tables

#### 16S

In [15]:
gomecc_16S.columns

Index(['id', 'occurrenceID', 'organismQuantity', 'materialSampleID', 'eventID',
       'eventDate', 'samplingProtocol', 'sampleSizeValue', 'locationID',
       'waterBody', 'locality', 'minimumDepthInMeters', 'maximumDepthInMeters',
       'decimalLatitude', 'decimalLongitude', 'geodeticDatum',
       'verbatimIdentification', 'identificationRemarks', 'taxonID',
       'scientificNameID', 'scientificName', 'nameAccordingTo', 'kingdom',
       'phylum', 'class', 'order', 'family', 'genus', 'taxonRank', 'ASV',
       'hash', 'parentEventID', 'markerGene'],
      dtype='object')

In [31]:
gomecc_16S_metadata = gomecc_16S[['parentEventID', 'materialSampleID', 'eventID', 'eventDate', 'samplingProtocol', 'locationID',
                                 'waterBody', 'locality', 'minimumDepthInMeters', 'decimalLatitude', 'decimalLongitude']]
# Need to fill in some missing metadata!
gomecc_16S_metadata['waterBody'] = gomecc_16S_metadata['waterBody'].fillna('Mexico, Gulf of')
gomecc_16S_metadata['# ASVs'] = 1
gomecc_16S_metadata_grouped = gomecc_16S_metadata.groupby(['parentEventID', 'materialSampleID', 'eventID', 'eventDate', 'samplingProtocol', 'locationID',
                                 'waterBody', 'locality', 'minimumDepthInMeters', 'decimalLatitude', 'decimalLongitude']).sum().reset_index()

/var/folders/df/9pc0s5c92v9637mf3mll4y5c0000gn/T/ipykernel_60916/2782440382.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gomecc_16S_metadata['# ASVs'] = 1

#### 18S

In [46]:
gomecc_18S_metadata = gomecc_18S[['parentEventID', 'materialSampleID', 'eventID', 'eventDate', 'samplingProtocol', 'locationID',
                                 'waterBody', 'locality', 'minimumDepthInMeters', 'decimalLatitude', 'decimalLongitude']]
# Need to fill in some missing metadata!
gomecc_18S_metadata['waterBody'] = gomecc_18S_metadata['waterBody'].fillna('Mexico, Gulf of')
gomecc_18S_metadata['# ASVs'] = 1
gomecc_18S_metadata_grouped = gomecc_18S_metadata.groupby(['parentEventID', 'materialSampleID', 'eventID', 'eventDate', 'samplingProtocol', 'locationID',
                                 'waterBody', 'locality', 'minimumDepthInMeters', 'decimalLatitude', 'decimalLongitude']).sum().reset_index()

/var/folders/df/9pc0s5c92v9637mf3mll4y5c0000gn/T/ipykernel_60916/3876815864.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gomecc_18S_metadata['waterBody'] = gomecc_18S_metadata['waterBody'].fillna('Mexico, Gulf of')
/var/folders/df/9pc0s5c92v9637mf3mll4y5c0000gn/T/ipykernel_60916/3876815864.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gomecc_18S_metadata['# ASVs'] = 1

#### Save tables

In [10]:
gomecc_16S_metadata_grouped.to_csv('GOMECC_16S_metadata_table.csv', index=None)
gomecc_18S_metadata_grouped.to_csv('GOMECC_18S_metadata_table.csv', index=None)